### ISSUE TITLE
Game not does recognise my ZIP

### ISSUE THREAD

**Issue by Danjb1** [cmfcmf/Anno2018#1]
I'm really interested in trying this, but when I try to upload a ZIP file containing my Anno resources I did an error message about my ZIP not having the correct format. I had a quick glance at the code and I saw that it looks for a "GFX" folder. However, this folder *is* present in my ZIP file. What am I missing?

**Comment by cmfcmf** [comment]
Hi @Danjb1, 
thank you for trying! Unfortunately, I haven't gotten around to writing some more docs on the zip format and how to get started. However, I made some changes to the zip detection code today, the new code is much simpler and looks like this:
https://github.com/cmfcmf/Anno2018-js/blob/5db2617f35b11889a99027a6c0d5d942faadfcd6/src/util/util.ts#L38-L44

It should now more reliably detect the anno root folder within the zip file. Let me know if it works. If not, could you post a screenshot of the folders within your zip file?

**Comment by SearchAndDestroy** [comment]
I bought the game via gog.com and installed it in ```C:\GOG Games\Anno 1602 - Creation of a New World``` and I just used 7zip to zip ```Anno 1602 - Creation of a New World``` and used that file for both files since I don't know which one is the game and which one is a save and it it recognized and I can start a game. I din't test further.

**Comment by Danjb1** [comment]
Thanks for the quick response. The upload seems to work now, but I still can't get the game to run. It says "Upload finished. The page will now refresh." and sure enough, the page refreshes and puts me right back to the upload screen.

**Comment by cmfcmf** [comment]
> Thanks for the quick response. The upload seems to work now, but I still can't get the game to run. It says "Upload finished. The page will now refresh." and sure enough, the page refreshes and puts me right back to the upload screen.

Alright, could you open your browser's console (which browser are you using?) by pressing `F12` and switch to the `Console` tab? Then please reload the page and tell me if you see any errors in your console.

![grafik](https://user-images.githubusercontent.com/2145092/43802570-7cba4efa-9a96-11e8-94ee-9ddc15f3fcc1.png)

**Comment by Danjb1** [comment]
I can see it copying a bunch of files when I upload the ZIP, but it seems to be failing when I upload the save:

```
Unhandled promise rejection 
Object { message: "'/saves' already exists", … }
```

**Comment by cmfcmf** [comment]
> I can see it copying a bunch of files when I upload the ZIP, but it seems to be failing when I upload the save:

That's odd. I've just pushed a few more changes, including more detailed instructions and progress updates without the need to open the console. If you'd like, please try resetting the uploaded files using the "Reset all files" button and then try to upload your Anno 1602 zip file again.
Note that you don't have to upload a savegames separately, if they are already included within your zip file.

**Comment by Danjb1** [comment]
Thanks @cmfcmf, I'm loving your work. The new instructions look really nice.

I just hit "Reset all files" and tried uploading again, but my upload progress shows the same error as before:

```
ERROR: The upload failed.
ERROR: '/saves' already exists
INFO: Copying '.gam' files from 'SAVEGAME/' to '/saves'.
INFO: Copying 'mit44.scp' to '/islands/south/mit44.scp'.
INFO: Copying 'mit43.scp' to '/islands/south/mit43.scp'.
INFO: Copying 'mit47.scp' to '/islands/north/mit47.scp'.
INFO: Copying 'mit42.scp' to '/islands/south/mit42.scp'.
INFO: Copying 'mit46.scp' to '/islands/north/mit46.scp'.
INFO: Copying 'mit41.scp' to '/islands/south/mit41.scp'.
INFO: Copying 'mit45.scp' to '/islands/north/mit45.scp'.
INFO: Copying 'mit40.scp' to '/islands/south/mit40.scp'.
INFO: Copying 'mit44.scp' to '/islands/north/mit44.scp'.
INFO: Copying 'mit39.scp' to '/islands/south/mit39.scp'.
...
```

**Comment by Danjb1** [comment]
If it helps, here are the contents of my ZIP file:

```
/d/tmp/1602 $ \ls -1 --group-directories-first
GADDATA
Gadedit
GFX
MGFX
MUSIC8
NOKLIMA
NORD
NORDNAT
'Own Scenarios'
SAMPLES
SAVEGAME
SGFX
SPEECH8
SUED
SUEDNAT
Szenes
TOOLGFX
VIDEOSMK
1602.EXE
1602Edit.exe
Config.exe
editor.cod
Editor.dll
figuren.cod
Game.dat
haeuser.cod
Language.dll
Maxnet.dll
Maxsound.dll
MFC42.DLL
MSVCRT.DLL
MSVCRTD.DLL
ReadMe.rtf
SMACKW32.DLL
text.cod
Un1602.isu
```

I am using Anno 1602 Gold Edition.

**Comment by cmfcmf** [comment]
Okay :( Which browser and OS are you using?

**Comment by cmfcmf** [comment]
> Okay :( Which browser and OS are you using?

Hey @Danjb1, can you tell me your browser and OS?

**Comment by Danjb1** [comment]
Sorry I missed your last comment! I'm on Windows 10 and using Firefox. Think I might have tried Chrome as well but I can't remember now.

**Comment by cmfcmf** [comment]
> Sorry I missed your last comment! I'm on Windows 10 and using Firefox. Think I might have tried Chrome as well but I can't remember now.

No worries, thank you 👍 I start to think that the polyfill for the FileAPI that I use in Firefox is buggy. The error says that the `/saves` directory already exists, however, just before uploading files, the whole in-browser filesystem [is deleted](https://github.com/cmfcmf/Anno2018-js/blob/master/src/upload.ts#L89). I suspect that something goes wrong there. If you had some time and were to try again, it'd be amazing if you could try
- Firefox in Incognito Mode 
- Chrome

Should the upload work in Incognito Mode, you could try to execute the following code in your browser's console in non-Incognito Mode to manually delete the file database and see if the upload works after that:
```js
var req = indexedDB.deleteDatabase("http_christianflach.de_Persistent");
req.onsuccess = () => console.log('success');
req.onerror = () => console.log('error');
req.onblocked = () => console.log('blocked');
```

I hope it helps!

**Comment by Danjb1** [comment]
# Chrome

 - The game loads, although I see a warning about not finding any music or video files, even though I copied the folders across from the CD.

 - The menus are a little cut-off at the bottom, is this a known issue?

 - I can load scenarios and drag the map around. The islands are separated by blackness. Can't seem to do much else but I'm guessing that's as far as you've got with the project so far?

# Firefox (Private Window)

 - The instructions aren't even displayed, I just see:
 
    > Anno 2018, version 3f8d335, made by @cmfcmf. The sourcecode can be found at GitHub.

 - I get a console error:

        Unhandled promise rejection 
        error { target: IDBOpenDBRequest, isTrusted: true, eventPhase: 0, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 567, cancelBubble: false, originalTarget: IDBOpenDBRequest, … }
        es6.promise.js:110
        D/</e<
        es6.promise.js:110
        nICZ/t.exports
        _perform.js:3:12
        D/<
        es6.promise.js:104
        MfQN/t.exports
        _invoke.js:5
        <anonymous>
        _task.js:35
        m
        _task.js:21
        b
        _task.js:25

**Comment by cmfcmf** [comment]
Hi, sorry for the late response:

> * The game loads, although I see a warning about not finding any music or video files, even though I copied the folders across from the CD.

Hmm, that's odd. Have you ever solved this issue? If it persists, could you please open a new issue on that topic? 💯 

> * The menus are a little cut-off at the bottom, is this a known issue?

Yes - the game currently takes up a fixed percentage of your browser window. If your window is not high enough, the game is cut off at the bottom.
 
> * I can load scenarios and drag the map around. The islands are separated by blackness. Can't seem to do much else but I'm guessing that's as far as you've got with the project so far?

Yes, exactly :+1:
