### ISSUE TITLE
COD Parsing

### ISSUE THREAD

**Issue by siredmar** [cmfcmf/Anno2018#4]
Hi!
Ich bin auf der Suche nach den Informationen, wie du mit den encodeten COD Dateien umgehst. 
In deinem Anno2018-godot Projekt hattest du das ja mittels Regex geloest um eine JSON Datei zu erzeugen. Wo finde ich das denn hier?

**Comment by cmfcmf** [comment]
Hi @siredmar,

der COD-Parser findet sich hier: https://github.com/cmfcmf/Anno2018/blob/master/src/parsers/COD/cod-parser.ts Der dient aber nur dazu, die Dateien zu "entschlüsseln". Das wirkliche Parsen nach JSON geschieht hier: https://github.com/cmfcmf/Anno2018/blob/master/src/parsers/DAT/dat-parser.ts

Wenn du dieses Repo runterlädst, Node.js und Yarn installierst, kannst du den Parser auch ausprobieren:
```
yarn install
yarn run cod-converter path/to/anno/haeuser.cod /tmp/haeuser.dat
yarn run dat-converter /tmp/haeuser.dat /tmp/haeuser.json
```

**Comment by siredmar** [comment]
Danke!
