### ISSUE TITLE
Animationen 

### ISSUE THREAD

**Issue by siredmar** [cmfcmf/Anno2018#6]
Hi!
Ich wundere mich gerade, wie die Animationen der verschiedenen Sachen funktionieren. 
Ich habe die Daten aus der haeuser.cod vorliegen. Korrigiere mich bitte, wenn ich falsch liege:
In den Objekten der haeuser.cod sind animationsparameter für Gebäude und Terrain (Wasser, Küste, Felder,... ) enthalten.
Für Figuren (Karren, Soldaten, Ureinwohner, Hirsch,...) gibt es jeweils eine oder mehrere verkettete animatiinsparameter in figuren.cod. 

Konkret beschäftige ich mich gerade mit der Animation von Gebäuden und Terrain. 
Ich hab deinen Animations-Handler gesehen. 
https://github.com/cmfcmf/Anno2018/blob/fff535e345b562bbf29c59bf6e985bd9c468a3b0/src/game/animation-renderer.ts#L39
Behandelst du Animationen von Gebäuden/Terrain gleich wie von den Figuren?
Konkret scheitere ich an der Berechnung des korrekten Index für die neue Textur, die angezeigt werden soll.
Die Daten  AnimAnz, AnimAdd, AnimTime und AnimFrame liegen je nach Feld zufreifbar vor. 
Kannst du mir da erklären, wie das funktioniert?

**Comment by cmfcmf** [comment]
Hi @siredmar, 
entschuldige die späte Antwort, deine Fragen sind bei mir im Postfach untergegangen.

> In den Objekten der haeuser.cod sind animationsparameter für Gebäude und Terrain (Wasser, Küste, Felder,... ) enthalten.
> Für Figuren (Karren, Soldaten, Ureinwohner, Hirsch,...) gibt es jeweils eine oder mehrere verkettete animatiinsparameter in figuren.cod.

Genau, wobei die figuren.cod z.B. auch Rauch und Schatten beinhaltet.

> Konkret beschäftige ich mich gerade mit der Animation von Gebäuden und Terrain.
> Behandelst du Animationen von Gebäuden/Terrain gleich wie von den Figuren?

Aktuell ist bei mir nur das Terrain (z.B. Wasser) und Gebäude animiert (z.B. die Eisenschmelze), Figuren habe ich noch kein animiert.

> Konkret scheitere ich an der Berechnung des korrekten Index für die neue Textur, die angezeigt werden soll.
> Die Daten AnimAnz, AnimAdd, AnimTime und AnimFrame liegen je nach Feld zufreifbar vor.
> Kannst du mir da erklären, wie das funktioniert?

Hast du das mittlerweile herausfinden können? Grundsätzlich solltest du das aus dem `AnimationRenderer` herauslesen können – aber z.B. Figuren habe ich bisher noch wenig bis gar nicht behandelt.
